### ISSUE TITLE
Subject Line not showing typed characters

### ISSUE THREAD

**Issue by ThermoNuclearPanda** [dcondrey/n1-monokai#3]
The subject line not showing stuff that is typed. 

See below.

<img width="782" alt="screen shot 2016-05-15 at 21 44 05" src="https://cloud.githubusercontent.com/assets/6700403/15280545/558c7c90-1ae6-11e6-8eeb-b925d7916c2a.png">
<img width="825" alt="screen shot 2016-05-15 at 21 44 19" src="https://cloud.githubusercontent.com/assets/6700403/15280546/558ebab4-1ae6-11e6-909d-aeaf563a6b02.png">

**Comment by oldhickory30** [comment]
Unable to enter text in the subject line as well!
